name: flow control
on: push

jobs:
  job1:
    name: Hello
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step1.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::Hello"

  job2:
    name: World!
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step2.outputs.test }}
    steps:
      - id: step2
        run: echo "::set-output name=test::World!"
  
  job3:
    name: Hello World!
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - run: echo ${{needs.job1.outputs.output}} ${{needs.job2.outputs.output}}

  